### ISSUE TITLE
Save order method called for non HPOS installations

### ISSUE THREAD

**Issue by pawelkmpt** [godaddy-wordpress/woocommerce-sequential-order-numbers#34]
After recent merge of #33 and update on our site, one of the 3rd party plugins started inserting its meta twice instead of just once. Xdebug led me to this line:

https://github.com/godaddy-wordpress/woocommerce-sequential-order-numbers/blob/2e82e5014c111c6687ef2719fe9176f88b0e56ae/woocommerce-sequential-order-numbers.php#L354-L355

Comment says `save()` should be triggered for HPOS installations but there's no condition checking it. Once I added it, double meta is no longer a problem.

```php
// with HPOS we need to trigger a save to update the order number or it won't persist by using the direct query above alone
if ( $using_hpos ) {
    $order->save();
}
```

@unfulvio-godaddy could you verify?

cc @lkraav

**Comment by lkraav** [comment]
@unfulvio-godaddy @unfulvio do you think you could patch this up, or at least confirm the findings so we could hotfix our live copy of the plugin code?

**Comment by unfulvio-godaddy** [comment]
hey @lkraav @pawelkmpt sorry for the late reply I was on holiday last week -- I'll try to replicate and issue a new release if that's the case (from the looks of it though this may be right that we need the method only in HPOS sites; this was a semi-copypasta from the pro version of the plugin where the code is slightly different though - and likely does not require patching up)

thanks for opening this and again apologies for the late reply
